run_name: OLMo-400M
seed: 6198
dry_run: false
no_pre_train_checkpoint: true

wandb:
  name: ${run_name}
  project: anonymous-project
  group: OLMo-150M-AdamW
  log_interval: 10
  entity: null

model:
  d_model: 768
  n_heads: 12
  n_layers: 16
  mlp_ratio: 1
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: false
  clip_qkv: null
  include_bias: false
  block_type: moe
  layer_norm_type: rms
  layer_norm_with_affine: true
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: null
  moe_config:
    top_k: 4
    num_experts: 32
    z_loss_weight: 0.001
    lb_loss_weight: 0.01
    hidden_size: 1536
    shared_mlp:
      hidden_size: 1536

compile: null

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  eps: 1.0e-8
  weight_decay: 0.1
  decay_norm_and_bias: true
  decay_embeddings: true
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 5000
  alpha_f: 0.1
  warmup_min_lr: 0

tokenizer:
  identifier: allenai/OLMo-7B-0424
  truncate_direction: right

save_folder: runs/${run_name}
remote_save_folder: null
save_overwrite: true

save_interval: 5000
save_interval_ephemeral: null
save_num_checkpoints_to_keep: -1
sharded_checkpointer: olmo_core

save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 2ep
global_train_batch_size: 1024
device_train_microbatch_size: 4

precision: amp_bf16
distributed_strategy: fsdp

fsdp:
  wrapping_strategy: by_block
  precision: mixed
  sharding_strategy: FULL_SHARD

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

eval_interval: 5000
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}

data:
  pad_direction: right
  num_workers: 32
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  timeout: 0
  paths:
    - /path/to/data/dataset/part-00-00000.npy